slavest:
  api_token: <%= ENV['SLAVEST_API_TOKEN'] %>
  rails:
    urls:
      base: http://localhost:3000
    paths:
      everests:
        new: /everests/new
      auth: /auth
      test: /test
slack:
  api_token: <%= ENV['SLACK_API_TOKEN'] %>
