default: &default
  slack:
    api_token: <%= ENV['SLACK_API_TOKEN'] %>
  slavest:
    api_token: <%= ENV['SLAREST_API_TOKEN'] %>
    bot_names:
      everest: Everest君
  errors:
    systems:
      messages:
        invalid_param: 予期せぬパラメータが渡されました。
        user_or_channel_presence: DBに存在しないUserもしくはChannelへの参照が起きました。
  everests:
    urls:
      base: http://192.168.20.2:24080
      get_emotion: /calcEmotion?text=
  models:
    emotion:
      emovalue_number_digits: 5
  controllers:
    emotions:
      messages:
        ok: OK
        user_not_found: WORN - 存在しないユーザです
        not_used_emotion: INFO - 対象ユーザではありません

development:
  <<: *default

test:
  <<: *default
  slack:
    api_token: <%= ENV['SLACK_API_TOKEN_TEST'] %>
  slavest:
    api_token: <%= ENV['SLAREST_API_TOKEN_TEST'] %>
    bot_names:
      everest: Test

production:
  <<: *default
