# A sample Gemfile
source "https://rubygems.org"

ruby '2.2.2'
gem "simple_slack"
gem 'activesupport'
gem 'activerecord'

# pryを使うgem
gem 'pry-rails'
gem 'pry-doc'
gem 'pry-byebug'
gem 'pry-stack_explorer'
gem 'parallel'
