slavest:
  api_token: <%= ENV['SLAVEST_API_TOKEN'] %>
  rails:
    urls:
      base: http://localhost:3000
    paths:
      everests:
        new: /everests/new
        show: /everests/show
      auth: /auth
      test: /test
slack:
  api_token: <%= ENV['SLACK_API_TOKEN'] %>
everests:
  urls:
    base: http://192.168.20.2:11180
    gets:
      emotion: /calcEmotion?text=
